#!/usr/bin/env bash

###############################################################################
# PREPARATIONS
###############################################################################

export DOTS=$(dirname $(realpath -s $0)); cd "$DOTS"
export PATH=~/.gem/ruby/2.5.0/bin:$PATH

test ! -d .ricecooker && git clone https://github.com/maxadamski/ricecooker .ricecooker

. .ricecooker/ricecooker.sh

rice_template_hashes=(colors.yml)
rice_verbosity=2

# You might ask what is this heresy, but if you don't like it, don't use it ;)
# It saves a lot of keystrokes, you know...
shopt -s expand_aliases
alias '+'='rice::exec --failable'
alias '!'='rice::exec'
alias pkg='rice::exec -c 6 17 sudo xbps-install -Sy'


###############################################################################
# HELPER FUNCTIONS
###############################################################################

linkd() {
	local src="$(realpath "$1")"
	local dst="$2"
	local makedirs=true
	if [[ $makedirs == true ]]; then
		mkdir -p "$(dirname "$dst")"
	fi
	ln -Tfs "$src" "$dst"
}

linkf() {
	local src=()
	while (( $# > 1 )); do
		src+=("$(realpath "$1")")
		shift
	done
	local dst="$1"

	local makedirs=true
	if [[ $makedirs == true ]]; then
		if (( ${#src[@]} > 1 )); then
			mkdir -p "$dst"
		else
			mkdir -p "$(dirname "$dst")"
		fi
	fi
	ln -fs "${src[@]}" "$dst"
}



###############################################################################
# MODULES
###############################################################################

rice::add setup:void:desktop -m
setup:void:desktop() {
	rice_template_hashes+=(desktop.yml)
}

rice::add setup:void:laptop -m
setup:void:laptop() {
	rice_template_hashes+=(laptop.yml)
}

rice::add bootstrap:void -x
bootstrap:void() {
	pkg -u
	pkg void-repo-multilib void-repo-nonfree
	pkg ruby curl bsdtar
	gem install mustache --user-install
}

rice::add bootstrap:void:laptop -x
bootstrap:void:laptop() {
	+ sudo xbps-pkgdb -m hold linux
	pkg linux4.13 linux4.13-headers
}

rice::add system_packages:void
system_packages:void() {
	pkg \
		Adapta ConsoleKit2 Fritzing ImageMagick MultiMarkdown R Thunar \
		alsa-tools alsa-utils apulse atool baobab bluez \
		bspwm calc calcurse cgdb cgmanager clang cmake compton-git conky \
		cryptsetup curlftpfs dunst exfat-dkms exfat-utils exiftool fcitx \
		fcitx-configtool fcitx-mozc feh filezilla firefox fish-shell flex \
		font-fira-otf font-inconsolata-otf font-symbola fontmanager \
		fuse-sshfs gcolor2 gengetopt gftp git glances gnupg gparted \
		highlight htop inxi ipafont-fonts-otf kcov mdadm mozc mpc mpd mpv \
		mupdf mkfontdir mkfontscale ncmpcpp neofetch neovim nftables \
		noto-fonts-emoji noto-fonts-ttf ntfs-3g numlockx openjdk p7zip \
		pamixer papirus-icon-theme pass pavucontrol plank pmount polybar \
		pulsemixer pylint python python-pip python3 python3-pip qbittorrent \
		qjackctl qsynth qt5-styleplugins qt5ct ranger renameutils retroarch \
		rofi rstudio ruby rust rxvt-unicode sc-im scrot sct setxkbmap \
		shellcheck subversion sxhkd sxiv thunderbird tig tmux udevil unp \
		unrar unzip urxvt-perls uzbl uzbl-tabbed w3m w3m-img \
		xbanish xboxdrv xcompmgr xcursor-vanilla-dmz-aa xdotool xev \
		xf86-input-joystick xlunch xmodmap xorg-minimal xrandr xrdb xset \
		xsetroot xtools youtube-dl zathura zathura-djvu zathura-pdf-mupdf \
		zathura-ps zip
}

rice::add system_packages:void:desktop
system_packages:void:desktop() {
	+ pkg \
		nvidia
}

rice::add system_packages:void:laptop
system_packages:void:laptop() {
	+ pkg \
		xf86-video-nouveau \
		xf86-video-intel \
		tlp
}

rice::add system_packages_big:void -x
system_packages_big:void() {
	+ pkg \
		virtualbox-ose \
		libreoffice \
		texlive-bin \
		wine-32bit 
}

rice::add system_config:void
system_config:void() {
	+ rice::template --sudo -m 600 system/blacklist.conf.mustache /etc/modprobe.d/blacklist.conf
	+ rice::template --sudo -m 644 system/grub.mustache /etc/default/grub
	+ rice::template --sudo -m 640 X11/xorg.conf.mustache /etc/X11/xorg.conf
	+ sudo install -Dm644 system/rc.conf /etc/rc.conf
	+ sudo install -Dm644 system/sshd_config /etc/ssh/sshd_config
	+ -q sudo update-grub
}

rice::add system_config:void:laptop
system_config:void:laptop() {
	+ sudo install -Dm644 system/tlp /etc/default/tlp
}

rice::add system_services:void
system_services:void() {
	+ sudo ln -sfT /etc/sv/alsa /var/service/alsa
	+ sudo ln -sfT /etc/sv/bluetoothd /var/service/alsa
	+ sudo ln -sfT /etc/sv/cgmanager /var/service/alsa
	+ sudo ln -sfT /etc/sv/consolekit /var/service/alsa
	+ sudo ln -sfT /etc/sv/dbus /var/service/alsa
}

rice::add system_services:void:laptop -x
system_services:void:laptop() {
	+ sudo ln -s /etc/sv/tlp /var/service/
}

rice::add system_keychain:void -x
system_keychain:void() {
	! test -d keychain
	+ sudo mkdir -p /etc/certificates
	+ sudo install -Dm640 keychain/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf
	+ sudo install -Dm644 keychain/adena-ca.pem /etc/certificates/
	+ sudo install -Dm644 keychain/edu-ca.pem /etc/certificates/
	+ sudo install -Dm600 keychain/eduroam.crt /etc/certificates/
	+ sudo install -Dm600 keychain/eduroam.key /etc/certificates/
}

rice::add user_packages -x
user_packages() {
	+ pip3 install --user \
		pygments neovim wheel pywal
}

rice::add user_documents -x
user_documents() {
	+ mkdir -p ~/{Desktop,Documents,Downloads,Pictures,Music,Videos}
	+ mkdir -p ~/.local/{bin,etc,opt,share}
	+ mkdir -p ~/.local/share/{themes,icons,fonts}

	+ linkd ~/.local/share/themes ~/.themes
	+ linkd ~/.local/share/icons ~/.icons
	+ linkd ~/.local/share/fonts ~/.fonts

	local URL_FONT_MATERIAL_ICONS='https://github.com/google/material-design-icons/blob/master/iconfont/MaterialIcons-Regular.ttf?raw=true'
	local URL_FONT_MONONOKI='https://github.com/madmalik/mononoki/releases/download/1.2/mononoki.zip'
	local URL_WALL_BONSAI='https://wallpaperscraft.com/image/bonsai_flower_pot_flower_117775_3840x2160.jpg'

	rice::info 'downloading font material icons'
	+ curl -sL "$URL_FONT_MATERIAL_ICONS" -o ~/.fonts/MaterialIcons-Regular.ttf
	rice::info 'downloading font mononoki'
	+ bsdtar -xf <(curl -sL "$URL_FONT_MONONOKI") -C ~/.fonts
	rice::info 'intstall current wallpaper'
	+ curl -sL "$URL_WALL_BONSAI" -o ~/Pictures/bonsai.jpg
}

rice::add user_config
user_config() {
	+ rice::template -m 750 fish/config.fish.mustache ~/.config/fish/config.fish
	+ rice::template kitty/kitty.conf.mustache ~/.config/kitty/kitty.conf

	+ linkd fish/functions ~/.config/fish/functions

	+ linkf bin/* ~/.local/bin
	+ linkf ncmpcpp/* ~/.config/ncmpcpp
	+ linkf ranger/* ~/.config/ranger
	+ linkf mpv/* ~/.config/mpv
	+ linkf vim/init.vim ~/.config/nvim/init.vim
	+ linkf shell/inputrc ~/.inputrc
	+ linkf shell/bashrc ~/.bashrc
	+ linkf git/config ~/.gitconfig
	+ linkf git/ignore ~/.gitignore
}

rice::add user_config:void
user_config:void() {
	+ rice::template -m 750 bspwm/bspwmrc.mustache ~/.config/bspwm/bspwmrc
	+ rice::template -m 750 X11/.xinitrc.mustache ~/.xinitrc
	+ rice::template X11/Xresources.mustache ~/.config/X11/Xresources
	+ rice::template polybar/config.mustache ~/.config/polybar/config
	+ rice::template gtk/settings.ini.mustache ~/.config/gtk-3.0/settings.ini
	+ rice::template gtk/.gtkrc-2.0.mustache ~/.gtkrc-2.0
	+ rice::template zathura/zathurarc.mustache ~/.config/zathura/zathurarc
	+ rice::template rofi/config.mustache ~/.config/rofi/config
	+ rice::template rofi/theme.rasi.mustache ~/.config/rofi/theme.rasi
	+ rice::template dunst/dunstrc.mustache ~/.config/dunst/dunstrc
	+ rice::template fontconfig/fonts.conf.mustache ~/.config/fontconfig/fonts.conf

	+ linkf sxhkd/sxhkdrc ~/.config/sxhkd/sxhkdrc
	+ linkf qutebrowser/config.py ~/.config/qutebrowser/config.py
	+ linkf compton/compton.conf ~/.config/compton.conf
	+ linkf mpd/mpd.conf ~/.config/mpd/mpd.conf

	# clear font cache
	+ mkfontscale ~/.local/share/fonts
	+ mkfontdir ~/.local/share/fonts
	+ fc-cache -f
	# restart some programs
	+ xrdb -merge ~/.config/X11/Xresources
	+ pkill -SIGUSR1 sxhkd
	+ killall polybar
	+ -q polybar right & disown
	+ -q polybar left & disown
	+ killall dunst
	+ -q dunst & disown
}

rice::add user_keychain -x
user_keychain() {
	! test -d keychain
	! install -Dm600 keychain/id_rsa ~/.ssh/id_rsa
	+ install -Dm600 keychain/authorized_keys ~/.ssh/authorized_keys
	+ install -Dm644 keychain/id_rsa.pub ~/.ssh/id_rsa.pub
	+ git clone git@bitbucket.com:maxadamski/password-store ~/.password-store
	+ gpg --import keychain/gpg_public.key
	+ gpg --import keychain/gpg_secret.key
}

rice::add user_keychain:void -x
user_keychain:void() {
	! test -d keychain
	+ linkd keychain/mozilla ~/.mozilla
	+ linkd keychain/thunderbird ~/.thunderbird
}


###############################################################################
# PASS TO RICECOOKER
###############################################################################

"$@"
