#!/usr/bin/env bash

HERE=$(dirname $(realpath -s $0))
cd $HERE

TEMPLATE_FUNCTION='template:mustache'
TEMPLATE_HASH=(colors.yml)
MUSTACHE_DIR=~/.gem/ruby/2.5.0/bin
export PATH=$MUSTACHE_DIR:$PATH
rice_verbosity=2
services=(dnsmasq nftables ppp samba)

shopt -s expand_aliases
alias '+'='rice::exec --failable'
alias '!'='rice::exec'

rice::add bootstrap:emperor:alpine -m
bootstrap:emperor:alpine() {
	+ apk update
	+ apk add curl
}

rice::add packages:emperor:alpine -x
packages:emperor:alpine() {
	+ apk add dnsmasq nftables vlan ppp samba nmap rsync \
		transmission-cli usb-modeswitch
	for service in "${services[@]}"; do
		+ rc-update add "$service"
	done
}

rice::add config:emperor:alpine
config:emperor:alpine() {
	+ sudo cp system/interfaces system/network/interfaces
	for service in "${services[@]}"; do
		+ rc-service "$service" restart
	done
}

rice::add keychain:emperor:alpine
keychain:emperor:alpine() {
	! test -d keychain
}
