#!/usr/bin/env bash

bspc monitor --reset-desktops {{bspwm.desktop_names}}

PADDING_H=30
PADDING_V=30

bspc config border_width   {{bspwm.border_width}}
bspc config window_gap     {{bspwm.window_gap}}

bspc config top_padding    {{bspwm.window_padding_y}}
bspc config bottom_padding {{bspwm.window_padding_y}}
bspc config right_padding  {{bspwm.window_padding_x}}
bspc config left_padding   {{bspwm.window_padding_x}}

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config normal_border_color   "{{color0}}"
bspc config focused_border_color  "{{color15}}"
bspc config presel_feedback_color "{{color2}}"
bspc config active_border_color   "{{color8}}"

